"""add new column to books

Revision ID: e4d8f2a4747f
Revises: ba25bedc88dd
Create Date: 2023-02-24 20:59:18.750216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d8f2a4747f'
down_revision = 'ba25bedc88dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'test_column')
    # ### end Alembic commands ###
